spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3307/coupon
    username: root
    password: 1234
  #  jpa:
  #    generate-ddl: true
  #    show-sql: false
  #    properties:
  #      hibernate:
  #        jdbc:
  #          batch_size: 1000
  #        order_inserts: true
  #        order_updates: true
  #        #        generate_statistics: true
  #        format_sql: true
  #    database: mysql
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    hibernate:
  #      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: coupon
    password: 1234
  cloud:
    bus:
      destination: coupon-dev-bus


logging:
  level:
    root: info

application:
  security:
    jwt:
      symmetric-signkey: KyjQRea02F25bQ1P0TAAcdFPN3FM/OtjwTiwhZudpuE=KyjQRea02F25bQ1P0TAAcdFPN3FM/OtjwTiwhZudpuE=
  info:
    message: dev-refresh